version: '3'
services:
  minio:
    image: 'minio/minio:RELEASE.2024-02-06T21-36-22Z.fips@sha256:3a320438cf10928e2ffefd9e13ec4df59f9fa3b82918965552b35310e1d32cc2'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9001'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
volumes:
  minio:
    driver: local