github:
  webhook:
    secret: "verysecret"
    signature-header: "x-hub-signature-256"
minio:
  endpoint: "localhost:9000"
  user:
    access-key-id: "Bry70IdY9j31keuwSyUM"
    secret-access-key: "CgL9X8905qcmRQA6eC1VqAXaBxBCPa2jsJpNr822"
  bucket: "github"
  useSSL: "false"